export const ProjectsData = [
    {
        name:"Calathea",
        id:"1",
        tech:"JavaScript, React, styled-components, Material-UI, Local-stage",
        decription:" is an online plant shop.",
        detail:"I designed and built this repsonsive React app. It allows you to learn about popular indoor plants. You can also learn about their water, sunlight and humidity requirments. The app allows you to login to book the plants you like.",
        demo:"https://calathea.netlify.app/",
        github:"https://github.com/miaypc/Calathea",
    },
    {
        name:"Currency Converter",
        id:"2",
        tech:"JavaScript, React, styled-components",
        api: "Open Exchange Rates API",
        apiLink: "https://openexchangerates.org/",
        decription:" is a real-time currency coverter.",
        detail:"I built this simple currency converter that converts currency rates between USD, EUR and CHF by using the",
        detail2: "to get real-time exhange rates. The app is not responsive because it was built to a fixed design.",
        demo:"https://currency-converter-in-realtime.netlify.app/",
        github:"https://github.com/miaypc/CurrencyConverter", 
    },
    {
        name:"Workademy",
        id:"3",
        tech:"Redux, React, styled-components, Material UI, SCSS",
        companyLink: "https://www.theworkademy.com/",
        decription:" is an oline education website helping teachers create classes for students.",
        detail:"This was part of a two-month-long extended project for our client. We built a website where teachers can put together online courses for their students. I designed and built this app with two teammates.",
        demo:"https://work-ade.netlify.app/",
        github:"https://github.com/miaypc/workademy", 
    },
    {
        name: "LacesUp",
        id:"4",
        companyLink: "https://www.lacesup.es/",
        tech: "Node.js, Express, MangoDB, Postman, React.js, Heroku",
        decription: " is an online shoelaces shop.",
        detail: "This was a two-day hackthon project for the client. Per their request, we built a user-facing page and an administration panel. The user-facing page gave customers the ability to see how LacesUp's shoelaces would look on different kinds of shoes. The administration panel enabled the company to easily add different kinds of shoelaces and shoes to the website. I worked as a back-end develper on this project.",
        github: "https://github.com/miaypc/laces_back",
        demo: "https://hardcore-austin-68e6f2.netlify.app/",
      },
    {
        name:"BEhERe",
        id:"5",
        tech:"React.js, Material UI, SCSS",
        api: "BrewDog API",
        apiLink: "https://punkapi.com/",
        decription:" is a React app for users to choose beers they like.",
        detail:"This was the second project I did at WCS. The app fetched different beers using the",
        detail2:"and allowed the user to filter them by flavor, alcohol level, and color.",
        demo:"https://behere-brewdog.netlify.app/#/",
        github:"https://github.com/miaypc/Beer", 
    },
    {
        name:"Heroship",
        id:"6",
        tech:"React.js, Material UI, SCSS",
        api: "SuperHero API",
        apiLink: "https://superheroapi.com/",
        decription:" is a superhero dating app.",
        detail:"This was a two-day hackathon project. I worked on with two teammates. We used the",
        detail2:"to show users pictures and descriptions of different superheroes. Users could try to find a good dating match for themselves among the superheroes.",
        demo:"https://zen-shaw-5af657.netlify.com/",
        github:"https://github.com/miaypc/Hero-ship", 
    }
]